# Generated by Django 5.2.12 on 2026-03-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=150)),
                ('payload', models.JSONField(verbose_name='Ham TTN Verisi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
