# Generated by Django 5.2.10 on 2026-04-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='nitrogen',
            field=models.FloatField(blank=True, null=True, verbose_name='Azot'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='phosphorus',
            field=models.FloatField(blank=True, null=True, verbose_name='Fosfor'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='potassium',
            field=models.FloatField(blank=True, null=True, verbose_name='Potasyum'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='soil_moisture',
            field=models.FloatField(blank=True, null=True, verbose_name='Toprak Nemi'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='soil_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Toprak Sıcaklığı'),
        ),
    ]
